import { NextIntlClientProvider, useLocale } from 'next-intl'
import { ReactNode } from 'react'

type Props = {
  children: ReactNode
  params: { locale: string }
}

export function generateStaticParams() {
  return [{ locale: 'en' }, { locale: 'pt-BR' }]
}

export const metadata = {
  title: 'Jacob Costa | Software Engineer',
  description: 'Generated by create next app',
}

// Even though this component is just passing its children through, the presence
// of this file fixes an issue in Next.js 13.4 where link clicks that switch
// the locale would otherwise cause a full reload.
export default async function RootLayout({ children, params }: Props) {
  const locale = useLocale()

  // Show a 404 error if the user requests an unknown locale
  if (params.locale !== locale) {
    console.log('params.locale', params.locale)
  }

  let messages
  try {
    messages = (await import(`../messages/${locale}.json`)).default
  } catch (error) {
    console.error(error)
  }

  return (
    <NextIntlClientProvider locale={locale} messages={messages}>
      {children}
    </NextIntlClientProvider>
  )
}
